### PR TITLE
Changes to topf calculation

### PR DESCRIPTION
**Pull request by caseyjhol**
I made some changes to the way topf is calculated to ensure that the scrollbar always reaches the bottom at the correct spot. I also upped the default acell value to 100, as I found 3 to be too slow, and not at all what I'm used to with my default scrollbar. Also removed the height set on the .scrollYou class. You can see an example of it in action here: http://jsfiddle.net/caseyjhol/LQnky/5/ using the red box on the left. The red box on the right is for comparison to normal select functionality.

### CODE REVIEW

**Comment by silviomoreto** [comment]
Hey @caseyjhol ! Ty. I tough I had fixed the size of height of the scroll bar to properly work.

Which OS are u using? Because on your example the scroll were too fast for me, and when I set it to 3, them it seems to work smoothly (Im using osx).

**Comment by caseyjhol** [comment]
I'm using Windows 8. Acceleration of 3 is painfully slow on my end. 100 is what my scroll speed is set to by default (compared one scroll in the left box to one scroll in the right box). Maybe we can compromise at 50?

**Comment by silviomoreto** [comment]
50 stills to fast for me (even 10 is fast)... probably we should analyze the os to apply the acceleration... idk.. do you have any other suggestion?

**Comment by caseyjhol** [comment]
That might be good. I'm playing around with a few different options to see if there are any other alternatives. It will be difficult to determine the best speed even after detecting OS, as it's a user-changeable preference.

**Pull request merged**
